version: "3.5"
services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "90:80"
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: rumon
        WORDPRESS_DB_PASSWORD: rumon@1234
        WORDPRESS_DB_NAME: wordpress1
    volumes:
      - wordpress1:/var/www/html
    depends_on:
      - db
       
  db:
    image: mariadb:latest
    restart: always
    environment:
        MARIADB_ROOT_PASSWORD: rootpasswd
        MYSQL_USER: rumon 
        MYSQL_PASSWORD: rumon@1234
        MYSQL_DATABASE: wordpress1
    volumes: 
      - dbdata:/var/lib/mysql
            
volumes:
  wordpress1:
  dbdata:

