version: "3.5"
services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "80:80"
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: rumon
        WORDPRESS_DB_PASSWORD: rumon@1234
        WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db
       
  db:
    image: mariadb:latest
    restart: always
    ports: 
      - "3306:3306"
    environment:
        MARIADB_ROOT_PASSWORD: rootpasswd
        MYSQL_USER: rumon 
        MYSQL_PASSWORD: rumon@1234
        MYSQL_DATABASE: wordpress
    volumes: 
      - dbdata:/var/lib/mysql
             
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
        PMA_ARBITRARY: 1
        PMA_HOST: db
           
            
volumes:
  wordpress:
  dbdata:

